<a href="https://colab.research.google.com/github/oroyansarah22/CHAPTER-8/blob/main/Genetic_Algorithm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
import numpy as np

var_values = [1,-3,4.5,2]
num_coeff = 4
pop_chrom = 10
sel_rate = 5

pop_size = (pop_chrom,num_coeff)

pop_new = np.random.uniform(low=-10.0, high=10.0,
size=pop_size)
print(pop_new)

[[ 5.8551558  -5.7058945  -6.63520553  3.76005896]
 [ 1.57462207 -1.33410696  9.07932404 -3.70670485]
 [ 0.64366454  9.13895575  6.0372909  -1.0183912 ]
 [ 1.44318664 -1.91792411  0.72455003  5.71291968]
 [ 5.18935771 -5.62288376  7.55908621  3.94097527]
 [-6.35505283 -4.45108494  8.46079301  6.30084896]
 [ 1.48376202 -0.18573639 -6.39649005  8.56042943]
 [-9.26223248  5.25089227 -8.67156423 -6.55636409]
 [ 3.84510931  3.50802497 -3.40178832  5.49681218]
 [-0.89146647  8.68306465 -7.40200653 -4.25135465]]


In [24]:
num_gen = 100

for k in range(num_gen):
  fitness = np.sum(pop_new *var_values, axis=1)
  par_sel = np.empty((sel_rate, pop_new.shape[1]))
  print("Current generation = ", k)
  print("Best fitness value : ", np.max(fitness))


Current generation =  0
Best fitness value :  63.95584747395983
Current generation =  1
Best fitness value :  63.95584747395983
Current generation =  2
Best fitness value :  63.95584747395983
Current generation =  3
Best fitness value :  63.95584747395983
Current generation =  4
Best fitness value :  63.95584747395983
Current generation =  5
Best fitness value :  63.95584747395983
Current generation =  6
Best fitness value :  63.95584747395983
Current generation =  7
Best fitness value :  63.95584747395983
Current generation =  8
Best fitness value :  63.95584747395983
Current generation =  9
Best fitness value :  63.95584747395983
Current generation =  10
Best fitness value :  63.95584747395983
Current generation =  11
Best fitness value :  63.95584747395983
Current generation =  12
Best fitness value :  63.95584747395983
Current generation =  13
Best fitness value :  63.95584747395983
Current generation =  14
Best fitness value :  63.95584747395983
Current generation =  15
Best fitne

In [25]:
for i in range(sel_rate):
  sel_id = np.where(fitness == np.max(fitness))
  sel_id = sel_id[0][0]
  par_sel[i, :] = pop_new[sel_id, :]
  fitness[sel_id]=np.min(fitness)

offspring_size=(pop_chrom-sel_rate, num_coeff)
offspring = np.empty(offspring_size)
crossover_lenght = int(offspring_size[1]/2)
for j in range(offspring_size[0]):
  par1_id = np.random.randint(0,par_sel.shape[0])
  par2_id = np.random.randint(0,par_sel.shape[0])
  offspring[j, 0:crossover_lenght] = par_sel[par1_id, 0:crossover_lenght]
  offspring[j, crossover_lenght:] = par_sel[par2_id, crossover_lenght:]

for m in range(offspring.shape[0]):
  mut_val = np.random.uniform(-1.0, 1.0)
  mut_id = np.random.randint(0,par_sel.shape[1])
  offspring[m, mut_id] = offspring[m, mut_id] + mut_val

pop_new[0:par_sel.shape[0], :] = par_sel
pop_new[par_sel.shape[0]:, :] = offspring

fitness = np.sum(pop_new *var_values, axis=1)
best_id = np.where(fitness == np.max(fitness))
print("Optimized coefficient values = ", pop_new[best_id,:])
print("Maximum value of y = ", fitness[best_id])

Optimized coefficient values =  [[[ 5.18935771 -5.7678082   7.55908621  3.94097527]]]
Maximum value of y =  [64.39062081]
